#!/usr/bin/env tsx
/**
 * [WHO]: Generates core/model/known-models.generated.ts from models.generated.ts
 * [FROM]: Reads core/lib/ai/src/models.generated.ts
 * [TO]: Produces core/model/known-models.generated.ts
 * [HERE]: scripts/generate-known-models.ts - extract known model metadata for discovery
 *
 * Usage: npx tsx scripts/generate-known-models.ts
 *
 * Parses the MODELS constant from models.generated.ts and extracts lightweight
 * metadata (id, name, api, contextWindow, maxTokens, reasoning, input, cost)
 * into a separate file consumed by the discovery system.
 */

import { readFileSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const projectRoot = join(__dirname, "..");

const INPUT_FILE = join(projectRoot, "core/lib/ai/src/models.generated.ts");
const OUTPUT_FILE = join(projectRoot, "core/model/known-models.generated.ts");

interface ExtractedModel {
	id: string;
	name: string;
	api: string;
	contextWindow: number;
	maxTokens: number;
	reasoning: boolean;
	input: string[];
	cost: { input: number; output: number; cacheRead: number; cacheWrite: number };
}

function extractModels(source: string): ExtractedModel[] {
	const models: ExtractedModel[] = [];
	const seen = new Set<string>();

	// Match each model entry: "model-id": { ... } satisfies Model<...>
	// We extract key fields from each model block
	const modelBlockRe = /"([^"]+)":\s*\{([^}]*?)\}\s*satisfies\s*Model<[^>]+>/gs;
	let match: RegExpExecArray | null;

	while ((match = modelBlockRe.exec(source)) !== null) {
		const id = match[1];
		if (!id || seen.has(id)) continue;
		seen.add(id);

		const block = match[2];

		// Extract fields from the block
		const getField = (field: string): string | undefined => {
			const re = new RegExp(`${field}:\\s*([^,\\n}]+)`);
			const m = re.exec(block);
			return m?.[1]?.trim();
		};

		const name = getField("name")?.replace(/^"(.*)"$/, "$1") ?? id;
		const api = getField("api")?.replace(/^"(.*)"$/, "$1") ?? "openai-completions";
		const reasoning = getField("reasoning") === "true";
		const contextWindow = parseInt(getField("contextWindow") ?? "128000", 10);
		const maxTokens = parseInt(getField("maxTokens") ?? "16384", 10);

		// Extract input array
		const inputMatch = /input:\s*\[([^\]]*)\]/.exec(block);
		const input: string[] = inputMatch
			? inputMatch[1]
					.split(",")
					.map((s) => s.trim().replace(/^"(.*)"$/, "$1"))
					.filter(Boolean)
			: ["text"];

		// Extract cost object
		const costMatch = /cost:\s*\{([^}]*)\}/.exec(block);
		const cost = { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 };
		if (costMatch) {
			const costBlock = costMatch[1];
			const getCostField = (field: string): number => {
				const re = new RegExp(`${field}:\\s*([\\d.]+)`);
				const m = re.exec(costBlock);
				return m ? parseFloat(m[1]) : 0;
			};
			cost.input = getCostField("input");
			cost.output = getCostField("output");
			cost.cacheRead = getCostField("cacheRead");
			cost.cacheWrite = getCostField("cacheWrite");
		}

		if (Number.isNaN(contextWindow) || Number.isNaN(maxTokens)) continue;

		models.push({ id, name, api, contextWindow, maxTokens, reasoning, input, cost });
	}

	return models;
}

function generateOutput(models: ExtractedModel[]): string {
	const lines = [
		"// This file is auto-generated by scripts/generate-known-models.ts",
		"// Do not edit manually — run 'npx tsx scripts/generate-known-models.ts' to update",
		"",
		'import type { KnownModelMetadata } from "./known-models.js";',
		"",
		`export const GENERATED_KNOWN_MODELS: KnownModelMetadata[] = [`,
	];

	for (const m of models) {
		lines.push(`\t{`);
		lines.push(`\t\tid: ${JSON.stringify(m.id)},`);
		lines.push(`\t\tname: ${JSON.stringify(m.name)},`);
		lines.push(`\t\tapi: ${JSON.stringify(m.api)},`);
		lines.push(`\t\tcontextWindow: ${m.contextWindow},`);
		lines.push(`\t\tmaxTokens: ${m.maxTokens},`);
		lines.push(`\t\treasoning: ${m.reasoning},`);
		lines.push(`\t\tinput: ${JSON.stringify(m.input)},`);
		lines.push(`\t\tcost: { input: ${m.cost.input}, output: ${m.cost.output}, cacheRead: ${m.cost.cacheRead}, cacheWrite: ${m.cost.cacheWrite} },`);
		lines.push(`\t},`);
	}

	lines.push("];");
	lines.push("");

	return lines.join("\n");
}

// --- Main ---

console.log(`Reading ${INPUT_FILE}...`);
const source = readFileSync(INPUT_FILE, "utf-8");

console.log("Extracting model metadata...");
const models = extractModels(source);
console.log(`Found ${models.length} models.`);

console.log(`Writing ${OUTPUT_FILE}...`);
const output = generateOutput(models);
writeFileSync(OUTPUT_FILE, output, "utf-8");

console.log("Done.");
