#!/usr/bin/env tsx
/**
 * [WHO]: Generates core/model/known-models.generated.ts from models.generated.ts
 * [FROM]: Reads core/lib/ai/src/models.generated.ts
 * [TO]: Produces core/model/known-models.generated.ts
 * [HERE]: scripts/generate-known-models.ts - extract known model metadata for discovery
 *
 * Usage: npx tsx scripts/generate-known-models.ts
 *
 * Parses the MODELS constant from models.generated.ts and extracts lightweight
 * metadata (id, name, api, contextWindow, maxTokens, reasoning, input, cost)
 * into a separate file consumed by the discovery system.
 */

import { readFileSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const projectRoot = join(__dirname, "..");

const INPUT_FILE = join(projectRoot, "core/lib/ai/src/models.generated.ts");
const OUTPUT_FILE = join(projectRoot, "core/model/known-models.generated.ts");

interface ExtractedModel {
	id: string;
	name: string;
	api: string;
	contextWindow: number;
	maxTokens: number;
	reasoning: boolean;
	input: string[];
	cost: { input: number; output: number; cacheRead: number; cacheWrite: number };
}

/**
 * Extract model entries by finding `"id": {` blocks terminated by `} satisfies Model<`.
 * Uses brace counting to handle nested objects (cost, compat).
 */
function extractModels(source: string): ExtractedModel[] {
	const models: ExtractedModel[] = [];
	const seen = new Set<string>();

	// Find all model key positions: "model-id": {
	const keyRe = /^\t\t"([^"]+)":\s*\{/gm;
	let keyMatch: RegExpExecArray | null;

	while ((keyMatch = keyRe.exec(source)) !== null) {
		const id = keyMatch[1];
		if (!id) continue;

		// Find the matching closing brace for this model object
		const blockStart = keyMatch.index + keyMatch[0].length;
		const block = extractBlock(source, blockStart);
		if (!block) continue;

		// Verify it ends with `satisfies Model<`
		const afterBlock = source.slice(blockStart + block.length, blockStart + block.length + 30);
		if (!afterBlock.includes("satisfies Model<")) continue;

		if (seen.has(id)) continue;
		seen.add(id);

		const model = parseModelBlock(id, block);
		if (model) models.push(model);
	}

	return models;
}

/**
 * Extract a brace-delimited block starting after the opening brace.
 * Returns the content between the braces (not including them).
 */
function extractBlock(source: string, start: number): string | null {
	let depth = 1;
	let i = start;
	while (i < source.length && depth > 0) {
		const ch = source[i];
		if (ch === "{") depth++;
		else if (ch === "}") depth--;
		if (depth === 0) return source.slice(start, i);
		i++;
	}
	return null;
}

function parseModelBlock(id: string, block: string): ExtractedModel | null {
	const getField = (field: string): string | undefined => {
		// Match `field: value` where value doesn't start with { or [
		const re = new RegExp(`^\\s*${field}:\\s*(.+?),?\\s*$`, "m");
		const m = re.exec(block);
		return m?.[1]?.trim().replace(/,$/, "").trim();
	};

	const name = getField("name")?.replace(/^"(.*)"$/, "$1") ?? id;
	const api = getField("api")?.replace(/^"(.*)"$/, "$1") ?? "openai-completions";
	const reasoning = getField("reasoning") === "true";

	const ctxStr = getField("contextWindow");
	const maxStr = getField("maxTokens");
	const contextWindow = ctxStr ? parseInt(ctxStr, 10) : 128000;
	const maxTokens = maxStr ? parseInt(maxStr, 10) : 16384;

	if (Number.isNaN(contextWindow) || Number.isNaN(maxTokens)) return null;

	// Extract input array: input: ["text", "image"]
	const inputMatch = /input:\s*\[([^\]]*)\]/.exec(block);
	const input: string[] = inputMatch
		? inputMatch[1]
				.split(",")
				.map((s) => s.trim().replace(/^"(.*)"$/, "$1"))
				.filter(Boolean)
		: ["text"];

	// Extract cost object (multi-line):
	// cost: {
	//   input: 0,
	//   output: 0,
	//   cacheRead: 0,
	//   cacheWrite: 0,
	// },
	const cost = { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 };
	const costBlockMatch = /cost:\s*\{([^}]*)\}/.exec(block);
	if (costBlockMatch) {
		const costBlock = costBlockMatch[1];
		const getCostField = (field: string): number => {
			const re = new RegExp(`${field}:\\s*([\\d.eE+-]+)`);
			const m = re.exec(costBlock);
			return m ? parseFloat(m[1]) : 0;
		};
		cost.input = getCostField("input");
		cost.output = getCostField("output");
		cost.cacheRead = getCostField("cacheRead");
		cost.cacheWrite = getCostField("cacheWrite");
	}

	return { id, name, api, contextWindow, maxTokens, reasoning, input, cost };
}

function generateOutput(models: ExtractedModel[]): string {
	const lines = [
		"// This file is auto-generated by scripts/generate-known-models.ts",
		"// Do not edit manually — run 'npx tsx scripts/generate-known-models.ts' to update",
		"",
		'import type { KnownModelMetadata } from "./known-models.js";',
		"",
		`export const GENERATED_KNOWN_MODELS: KnownModelMetadata[] = [`,
	];

	for (const m of models) {
		lines.push(`\t{`);
		lines.push(`\t\tid: ${JSON.stringify(m.id)},`);
		lines.push(`\t\tname: ${JSON.stringify(m.name)},`);
		lines.push(`\t\tapi: ${JSON.stringify(m.api)},`);
		lines.push(`\t\tcontextWindow: ${m.contextWindow},`);
		lines.push(`\t\tmaxTokens: ${m.maxTokens},`);
		lines.push(`\t\treasoning: ${m.reasoning},`);
		lines.push(`\t\tinput: ${JSON.stringify(m.input)},`);
		lines.push(`\t\tcost: { input: ${m.cost.input}, output: ${m.cost.output}, cacheRead: ${m.cost.cacheRead}, cacheWrite: ${m.cost.cacheWrite} },`);
		lines.push(`\t},`);
	}

	lines.push("];");
	lines.push("");

	return lines.join("\n");
}

// --- Main ---

console.log(`Reading ${INPUT_FILE}...`);
const source = readFileSync(INPUT_FILE, "utf-8");

console.log("Extracting model metadata...");
const models = extractModels(source);
console.log(`Found ${models.length} models.`);

if (models.length < 100) {
	console.error(`ERROR: Only extracted ${models.length} models — expected 600+. The source file format may have changed.`);
	process.exit(1);
}

console.log(`Writing ${OUTPUT_FILE}...`);
const output = generateOutput(models);
writeFileSync(OUTPUT_FILE, output, "utf-8");

console.log("Done.");
